# App name
service: backend-lambda-clone-01

#? Serverless Dotenv Plugin replaces this
# Enables .env file to be used
#useDotenv: true

plugins:
  - serverless-offline
  - serverless-plugin-common-excludes
  - serverless-plugin-include-dependencies
  - serverless-dotenv-plugin
provider:
  name: aws
  runtime: nodejs14.x
  stage: prod
  region: eu-west-1
  timeout: 30
  environment: #define env variables if needed

package:
  individually: true
  exclude:
    - ./**
  include:
    #- .env
    - node-modules/**

functions:
  backend-clone:
    name: backend-clone
    description: Demo backend for the Lambda deployment
    handler: dist/serverless.handler
    include:
      - 'dist/**/*'
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors:
            origins:
              - 'http://localhost:8000' # Replace with the allowed origin(s) for your frontend
            headers:
              - Content-Type
            allowCredentials: false

      #- http:
      #    method: ANY
      #    path: /health # Catch /health route
      #- http:
      #    method: ANY
      #    path: /todos # Catch /todos route
      #- http:
      #    method: ANY
      #    path: /todos/{any+} # Catch all todos routes
